-- Isolated fixture: inferred baseline schema for the CMS content model.
--
-- This file is NOT a production migration. It reconstructs the public tables
-- the CMS repository reads and writes (inferred from src/types,
-- src/app/actions/cms/** and supabase/migrations) so the throwaway local
-- Supabase instance can run the real Server Actions against real PostgREST /
-- GoTrue / Storage. The production project owns the authoritative schema;
-- this baseline exists only so the repo's own migrations can be applied in
-- order (several of them reference these tables).
--
-- It is applied as the FIRST migration in the isolated /tmp project, before
-- the repository's supabase/migrations/*.sql files are copied in.

-- ── Extensions used by the repo migrations ───────────────────────────────
create extension if not exists pgcrypto;

-- ── Content tables ───────────────────────────────────────────────────────

create table if not exists public.hero_section (
  id bigint primary key generated by default as identity,
  name text,
  role text,
  about text,
  propic text,
  "blurhashURL" text,
  resume_en text,
  resume_it text,
  shape text
);

create table if not exists public.i18n_translations (
  language text primary key,
  translations jsonb not null default '{}'::jsonb,
  privacy_policy text
);

create table if not exists public.contacts (
  id bigint primary key generated by default as identity,
  label text not null,
  icon text,
  link text,
  bg_color text,
  position integer not null default 0
);

create table if not exists public.skills_categories (
  id bigint primary key generated by default as identity,
  name text not null,
  position integer not null default 0
);

create table if not exists public.skills (
  id bigint primary key generated by default as identity,
  title text not null,
  icon text,
  invert boolean not null default false,
  category_id bigint references public.skills_categories (id) on delete cascade,
  "blurhashURL" text,
  link text,
  position integer
);

create table if not exists public.career_entries (
  id bigint primary key generated by default as identity,
  created_at timestamptz not null default now(),
  title text not null,
  company text not null,
  website_url text,
  logo text,
  blurhashurl text,
  location_en text,
  location_it text,
  remote text not null default 'full'
    check (remote in ('full', 'hybrid', 'onSite')),
  "startDate" text,
  "endDate" text,
  description_en text,
  description_it text,
  skills text,
  company_description_en text,
  company_description_it text
);

create table if not exists public.blog_posts (
  id bigint primary key generated by default as identity,
  created_at timestamptz not null default now(),
  title text,
  title_en text not null,
  title_it text not null,
  image text,
  description_en text,
  description_it text,
  body_en text,
  body_it text,
  "blurhashURL" text,
  post_tags text,
  views integer not null default 0,
  hidden boolean not null default false,
  author_id uuid references auth.users (id) on delete set null
);

create table if not exists public.portfolio_posts (
  id bigint primary key generated by default as identity,
  created_at timestamptz not null default now(),
  title_en text not null,
  title_it text not null,
  image text,
  source_link text,
  demo_link text,
  description_en text,
  description_it text,
  body_en text,
  body_it text,
  "blurhashURL" text,
  post_tags text,
  store_link text,
  fdroid_link text,
  website text,
  ios_store_link text,
  buttons jsonb,
  views integer not null default 0,
  hidden boolean not null default false,
  author_id uuid references auth.users (id) on delete set null
);

-- Singleton Layout settings. Null logos use bundled website assets; textual
-- VAT preserves leading zeroes and NULL keeps the website's default.
create table if not exists public.site_settings (
  id bigint primary key generated by default as identity,
  created_at timestamptz not null default now(),
  header_logo_dark text,
  header_logo_light text,
  footer_vat_number text
);

-- ── Internal CMS tables ─────────────────────────────────────────────────

create table if not exists public.cms_allowed_users (
  id bigint primary key generated by default as identity,
  created_at timestamptz not null default now(),
  email text unique,
  github_username text unique,
  role text not null default 'editor'
    check (role in ('admin', 'editor')),
  check (email is not null or github_username is not null)
);

create table if not exists public.user_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  email text,
  display_name text,
  avatar_url text,
  auth_provider text,
  github_username text
);

-- Personal data: service_role only. Mirrors
-- 20261004130000_add_project_requests.sql (boolean archive flag).
create table if not exists public.project_requests (
  id bigint primary key generated by default as identity,
  created_at timestamptz not null default now(),
  locale text not null default 'en' check (locale in ('en', 'it')),
  name text not null,
  email text not null,
  company text not null default '',
  website text not null default '',
  project_type text not null
    check (project_type in ('Website', 'Web app', 'Mobile app', 'Other')),
  budget text not null
    check (budget in ('< €1k', '€1–5k', '€5–15k', '€15k+')),
  timeline text not null
    check (timeline in ('ASAP', '1–2 months', '3–6 months', 'Flexible')),
  request text not null,
  consent boolean not null,
  archived boolean not null default false,
  archived_at timestamptz
);

create index if not exists project_requests_active_idx
  on public.project_requests (archived, created_at desc);

-- ── Grants (explicit; local auto-expose defaults may not apply) ─────────
grant usage on schema public to anon, authenticated, service_role;
grant select on all tables in schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public
  to service_role;
grant usage, select on all sequences in schema public
  to anon, authenticated, service_role;

-- project_requests is NOT public content: the blanket grants above reach it,
-- so this personal-data table is revoked again from anon/authenticated and
-- from PUBLIC (Supabase's default SELECT-to-PUBLIC).
revoke all on table public.project_requests from public;
revoke all on table public.project_requests from anon, authenticated;
grant select, insert, update, delete on table public.project_requests
  to service_role;
grant usage, select on sequence public.project_requests_id_seq
  to service_role;

-- ── RLS: content is publicly readable; CMS writes go through service_role ─
alter table public.hero_section enable row level security;
alter table public.i18n_translations enable row level security;
alter table public.contacts enable row level security;
alter table public.skills_categories enable row level security;
alter table public.skills enable row level security;
alter table public.career_entries enable row level security;
alter table public.blog_posts enable row level security;
alter table public.portfolio_posts enable row level security;
alter table public.cms_allowed_users enable row level security;
alter table public.user_profiles enable row level security;
alter table public.site_settings enable row level security;
alter table public.project_requests enable row level security;


drop policy if exists isolated_public_read on public.hero_section;
create policy isolated_public_read on public.hero_section
  for select using (true);

drop policy if exists isolated_public_read on public.i18n_translations;
create policy isolated_public_read on public.i18n_translations
  for select using (true);

drop policy if exists isolated_public_read on public.contacts;
create policy isolated_public_read on public.contacts
  for select using (true);

drop policy if exists isolated_public_read on public.skills_categories;
create policy isolated_public_read on public.skills_categories
  for select using (true);

drop policy if exists isolated_public_read on public.skills;
create policy isolated_public_read on public.skills
  for select using (true);

drop policy if exists isolated_public_read on public.career_entries;
create policy isolated_public_read on public.career_entries
  for select using (true);

drop policy if exists isolated_public_read on public.blog_posts;
create policy isolated_public_read on public.blog_posts
  for select using (true);

drop policy if exists isolated_public_read on public.portfolio_posts;
create policy isolated_public_read on public.portfolio_posts
  for select using (true);

drop policy if exists isolated_public_read on public.site_settings;
create policy isolated_public_read on public.site_settings
  for select using (true);

-- cms_allowed_users / user_profiles: no anon/authenticated policies. Only
-- service_role (BYPASSRLS) and the SECURITY DEFINER RPCs may read them.
-- project_requests joins them: no anon/authenticated policies either, since
-- it holds submitted personal data.

-- ── Auth → profile trigger (mirrors the production shape) ───────────────
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  insert into public.user_profiles
    (id, email, display_name, avatar_url, auth_provider, github_username)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'user_name',
      split_part(new.email, '@', 1)
    ),
    new.raw_user_meta_data ->> 'avatar_url',
    coalesce(new.raw_app_meta_data ->> 'provider', 'email'),
    new.raw_user_meta_data ->> 'user_name'
  )
  on conflict (id) do nothing;
  return new;
end;
$function$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── Fixture-only write audit ────────────────────────────────────────────
-- Records every committed insert/update/delete the real Server Actions make,
-- so integration/browser tests can assert observed writes. This table does
-- not exist in production and is only created in the isolated project.

create table if not exists public._fixture_writes (
  id bigint generated always as identity primary key,
  at timestamptz not null default now(),
  table_name text not null,
  operation text not null,
  row_id text,
  role_name text,
  new_row jsonb,
  old_row jsonb
);

grant select, insert, delete on public._fixture_writes
  to anon, authenticated, service_role;
grant usage, select on sequence public._fixture_writes_id_seq
  to anon, authenticated, service_role;

create or replace function public._fixture_log_write()
returns trigger
language plpgsql
set search_path = ''
as $function$
declare
  v_new jsonb := case when tg_op = 'DELETE' then null else to_jsonb(new) end;
  v_old jsonb := case when tg_op = 'INSERT' then null else to_jsonb(old) end;
  v_id text;
begin
  v_id := coalesce(v_new ->> 'id', v_old ->> 'id');
  insert into public._fixture_writes
    (table_name, operation, row_id, role_name, new_row, old_row)
  values (tg_table_name, tg_op, v_id, current_user, v_new, v_old);
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$function$;

do $do$
declare
  t text;
  audited text[] := array[
    'hero_section', 'i18n_translations', 'contacts', 'skills_categories',
    'skills', 'career_entries', 'blog_posts', 'portfolio_posts',
    'cms_allowed_users', 'user_profiles', 'project_requests',
    'site_settings'
  ];
begin
  foreach t in array audited loop
    execute format('drop trigger if exists _fixture_log_write on public.%I', t);
    execute format(
      'create trigger _fixture_log_write after insert or update or delete on public.%I for each row execute function public._fixture_log_write()',
      t
    );
  end loop;
end;
$do$;
