import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { PGlite } from '@electric-sql/pglite';
import { beforeAll, describe, expect, it } from 'vitest';

/**
 * Executes the public-content restoration migration against a real
 * Postgres (PGlite, WASM) seeded with the pre-migration public shape, and
 * asserts the resulting objects, ACL and idempotency — rather than reading
 * the SQL as text.
 *
 * What must hold before this file is ever applied to production:
 * - both tables appear with the dev-mirrored columns, defaults and checks;
 * - the four CMS-owned columns land on the existing tables WITHOUT
 *   touching their rows;
 * - site_settings stays publicly readable while project_requests stays
 *   service_role-only (personal data);
 * - replaying the whole file changes nothing (safe resume after a partial
 *   apply or a retried run).
 */

const migrationPath = fileURLToPath(
  new URL(
    '../../../supabase/migrations/20261010000000_restore_public_content_objects.sql',
    import.meta.url
  )
);

let db: PGlite;

async function hasPrivilege(
  role: string,
  table: string,
  privilege: string
): Promise<boolean> {
  const result = await db.query<{ allowed: boolean }>(
    `select has_table_privilege($1, $2, $3) as allowed`,
    [role, table, privilege]
  );
  return result.rows[0]?.allowed === true;
}

async function columnsOf(table: string): Promise<string[]> {
  const result = await db.query<{ column_name: string }>(
    `select column_name from information_schema.columns
     where table_schema = 'public' and table_name = $1`,
    [table]
  );
  return result.rows.map((row) => row.column_name);
}

beforeAll(async () => {
  db = new PGlite();
  await db.exec(
    'create role anon; create role authenticated; create role service_role;'
  );
  // Pre-migration public shape: content tables exist WITHOUT the new
  // CMS-owned columns, and one hero row already lives there.
  await db.exec(`
    create table public.hero_section (
      id bigint primary key generated by default as identity,
      propic text
    );
    create table public.portfolio_posts (
      id bigint primary key generated by default as identity,
      title_en text not null
    );
    create table public.skills (
      id bigint primary key generated by default as identity,
      title text not null
    );
    insert into public.hero_section (propic) values ('https://x.test/a.webp');
  `);
  const sql = await readFile(migrationPath, 'utf8');
  await db.exec(sql);
  // Replay proves idempotency: a retried or resumed apply is a no-op.
  await db.exec(sql);
}, 60_000);

describe('public content restoration', () => {
  it('creates site_settings with the dev-mirrored columns, minus retirements', async () => {
    expect(await columnsOf('site_settings')).toEqual([
      'id',
      'created_at',
      'footer_vat_number',
      'header_logo_dark',
      'header_logo_light',
    ]);
  });

  it('creates project_requests with the full intake contract', async () => {
    expect(await columnsOf('project_requests')).toEqual(
      expect.arrayContaining([
        'id',
        'created_at',
        'locale',
        'name',
        'email',
        'company',
        'website',
        'project_type',
        'budget',
        'timeline',
        'request',
        'consent',
        'archived',
        'archived_at',
      ])
    );
    await expect(
      db.exec(
        `insert into public.project_requests
         (locale, name, email, project_type, budget, timeline, request, consent)
         values ('xx', 'Mallory', 'm@example.com', 'Website', '€1k', 'ASAP', 'Hi', true)`
      )
    ).rejects.toThrow();
    const index = await db.query<{ count: number }>(
      `select count(*)::int as count from pg_indexes
       where schemaname = 'public' and indexname = 'project_requests_active_idx'`
    );
    expect(index.rows[0]?.count).toBe(1);
  });

  it('adds the CMS-owned columns without touching existing rows', async () => {
    expect(await columnsOf('hero_section')).toContain('shape');
    expect(await columnsOf('portfolio_posts')).toContain('buttons');
    expect(await columnsOf('skills')).toEqual(
      expect.arrayContaining(['link', 'position'])
    );
    const hero = await db.query<{ propic: string; shape: null }>(
      `select propic, shape from public.hero_section`
    );
    expect(hero.rows[0]).toEqual({
      propic: 'https://x.test/a.webp',
      shape: null,
    });
  });

  it('keeps site_settings publicly readable with exactly one policy', async () => {
    const rls = await db.query<{ relrowsecurity: boolean }>(
      `select relrowsecurity from pg_class
       where oid = 'public.site_settings'::regclass`
    );
    expect(rls.rows[0]?.relrowsecurity).toBe(true);
    const policies = await db.query<{ policyname: string }>(
      `select policyname from pg_policies
       where schemaname = 'public' and tablename = 'site_settings'`
    );
    expect(policies.rows.map((row) => row.policyname)).toEqual([
      'site_settings_public_read',
    ]);
    expect(await hasPrivilege('anon', 'public.site_settings', 'SELECT')).toBe(
      true
    );
    for (const privilege of ['INSERT', 'UPDATE', 'DELETE']) {
      expect(
        await hasPrivilege('anon', 'public.site_settings', privilege)
      ).toBe(false);
      expect(
        await hasPrivilege('authenticated', 'public.site_settings', privilege)
      ).toBe(false);
    }
    for (const privilege of ['SELECT', 'INSERT', 'UPDATE', 'DELETE']) {
      expect(
        await hasPrivilege('service_role', 'public.site_settings', privilege)
      ).toBe(true);
    }
  });

  it('keeps project_requests service_role-only with no policies', async () => {
    const policies = await db.query<{ count: number }>(
      `select count(*)::int as count from pg_policies
       where schemaname = 'public' and tablename = 'project_requests'`
    );
    expect(policies.rows[0]?.count).toBe(0);
    for (const role of ['anon', 'authenticated']) {
      for (const privilege of ['SELECT', 'INSERT', 'UPDATE', 'DELETE']) {
        expect(
          await hasPrivilege(role, 'public.project_requests', privilege)
        ).toBe(false);
      }
    }
    for (const privilege of ['SELECT', 'INSERT', 'UPDATE', 'DELETE']) {
      expect(
        await hasPrivilege(
          'service_role',
          'public.project_requests',
          privilege
        )
      ).toBe(true);
    }
  });

  it('hands identity sequences to service_role only', async () => {
    for (const sequence of [
      'public.site_settings_id_seq',
      'public.project_requests_id_seq',
    ]) {
      expect(
        (
          await db.query<{ allowed: boolean }>(
            `select has_sequence_privilege('service_role', $1, 'USAGE') as allowed`,
            [sequence]
          )
        ).rows[0]?.allowed
      ).toBe(true);
      expect(
        (
          await db.query<{ allowed: boolean }>(
            `select has_sequence_privilege('anon', $1, 'USAGE') as allowed`,
            [sequence]
          )
        ).rows[0]?.allowed
      ).toBe(false);
    }
  });
});
