-- 20261004120000_add_site_settings.sql
-- Header chrome the CMS owns: the per-theme logo URLs and the ordered nav
-- anchors, on a single-row configuration table.
--
-- Why a table and not `i18n_translations`: these are configuration (asset
-- URLs, element ids), not copy. They are not translated — the six nav items
-- are the same six in both locales — so burying them in the translations jsonb
-- would make them look like editor copy and pollute the delta-merge path.
--
-- Cardinality is honestly one row (the header exists once). A key/value table
-- would model six unrelated settings; a single typed row does not.
--
-- Every column is nullable on purpose. NULL means "never configured" and the
-- public site falls back to exactly what it rendered before this table
-- existed: the bundled `title-ws.png` / `title-ws-lightmode.png` assets and
-- the nav hrefs computed from the section ids. That is what makes this
-- migration a no-op for existing content.
--
-- `nav_anchors` is an ordered jsonb array of `{ id, anchor }`:
--
--   id:     'home' | 'skills' | 'career' | 'portfolio' | 'blog' | 'contacts'
--   anchor: fragment-safe element id, no leading '#' (null/'' = default)
--
-- The array is WRITTEN index-aligned with `header.buttons.N` (the nav labels
-- are also index-addressed, so alignment is what keeps a label and its
-- anchor on the same item). It is READ by `id`, so a reordered or
-- hand-edited row still lands on the right nav item. The scroll-spy and the
-- mobile drawer keep reading the sections' own `id=` attributes, which this
-- migration does not touch.

create table if not exists public.site_settings (
  id bigint primary key generated by default as identity,
  created_at timestamptz not null default now(),
  header_logo_dark text,
  header_logo_light text,
  nav_anchors jsonb
);

comment on table public.site_settings is
  'Single-row site configuration. Header chrome the CMS owns; NULL means "never configured" and the public site falls back to its bundled asset / computed href.';

comment on column public.site_settings.header_logo_dark is
  'Absolute URL of the dark-theme header logo. NULL renders the bundled title-ws.png; an empty string is treated as NULL by the reader.';

comment on column public.site_settings.header_logo_light is
  'Absolute URL of the light-theme header logo. NULL renders the bundled title-ws-lightmode.png; an empty string is treated as NULL by the reader. Resolved per theme, so storing one variant never blanks the other.';

comment on column public.site_settings.nav_anchors is
  'Ordered [{ id, anchor }] for the six nav items, written index-aligned with header.buttons.N and read by id. anchor is a fragment-safe element id with no leading #; NULL/empty falls back to the item id.';

-- ── Grants ───────────────────────────────────────────────────────────────
-- The public site reads this with the publishable (anon) key, so it needs
-- schema USAGE + SELECT. The CMS writes through the service-role client
-- (BYPASSRLS) and needs the DML privileges. Mirrors every other content
-- table in this project.
grant usage on schema public to anon, authenticated, service_role;
grant select on table public.site_settings to anon, authenticated;
grant select, insert, update, delete on table public.site_settings
  to service_role;
-- Sequence access goes to service_role only: anon/authenticated have no
-- DML on this table, so granting them the sequence would widen the surface
-- for no benefit.
grant usage, select on sequence public.site_settings_id_seq to service_role;

-- ── RLS: publicly readable, CMS-owned writes ─────────────────────────────
alter table public.site_settings enable row level security;

drop policy if exists site_settings_public_read on public.site_settings;
create policy site_settings_public_read on public.site_settings
  for select to anon, authenticated using (true);

-- REVERSIBLE
--   drop table if exists public.site_settings;
-- Dropping the table restores the site to its pre-CMS header: the bundled
-- logos and the computed nav hrefs. No other table references it.