-- 20261004130000_add_project_requests.sql
-- Incoming project requests from the public form (okazakee-ws RequestForm).
--
-- This is OPERATIONAL data, not public content: every row carries a real
-- name, an email address and free text a visitor typed. It therefore
--   - never joins the public cache-tag vocabulary (no revalidation event),
--   - never gets an anon/authenticated grant,
--   - is read and written only through the service-role clients
--     (okazakee-ws /api/requests for the INSERT, the CMS inbox action for
--     everything else).
--
-- Column names mirror the public form one-for-one, except `project_type`
-- (renamed from the form's `type` to avoid a bare SQL keyword) — the CMS
-- row mapper in `requestEntriesActions.ts` is the only place that translates.
--
-- ARCHIVE IS A BOOLEAN, NOT A STATUS COLUMN. The inbox only needs two
-- states (active / archived) and one predicate, `archived = false|true`;
-- an enum-shaped status column would add a third vocabulary (and a
-- CHECK constraint) for a distinction the product never draws. `archived_at`
-- records when the row was archived, which is the only extra fact a boolean
-- cannot answer on its own.

create table if not exists public.project_requests (
  id bigint primary key generated by default as identity,
  created_at timestamptz not null default now(),
  locale text not null default 'en'
    check (locale in ('en', 'it')),
  name text not null,
  email text not null,
  company text not null default '',
  website text not null default '',
  project_type text not null
    check (project_type in ('Website', 'Web app', 'Mobile app', 'Other')),
  budget text not null
    check (budget in ('< €1k', '€1–5k', '€5–15k', '€15k+')),
  timeline text not null
    check (timeline in ('ASAP', '1–2 months', '3–6 months', 'Flexible')),
  request text not null,
  consent boolean not null,
  archived boolean not null default false,
  archived_at timestamptz
);

comment on table public.project_requests is
  'Project requests submitted through the public form. Personal data: service_role only, no anon/authenticated grants, never publicly cached.';

comment on column public.project_requests.project_type is
  'Project type option (the public form field is named `type`).';

comment on column public.project_requests.archived is
  'Boolean archive flag: false = active inbox row, true = archived. The CMS filters on this single predicate.';

comment on column public.project_requests.archived_at is
  'When the row was archived; null while active.';

-- Active-first listing is the inbox default view.
create index if not exists project_requests_active_idx
  on public.project_requests (archived, created_at desc);

-- RLS on with NO policies: anon/authenticated own no rows, and service_role
-- bypasses RLS outright. This is belt-and-braces on top of the revoked
-- grants below.
alter table public.project_requests enable row level security;

-- Supabase tables default to SELECT granted to PUBLIC (anon/authenticated
-- inherit it), so revoke from `public` too — see
-- 20260818140002_revoke_public_select_on_allowlist.sql.
revoke all on table public.project_requests from public;
revoke all on table public.project_requests from anon, authenticated;

grant select, insert, update, delete on table public.project_requests
  to service_role;
grant usage, select on sequence public.project_requests_id_seq
  to service_role;

-- REVERSIBLE
--   drop table if exists public.project_requests;