-- 20261010000000_restore_public_content_objects.sql
--
-- Restores public-schema objects the website release reads but the
-- production database never received: the `site_settings` and
-- `project_requests` tables, plus four CMS-owned columns. Every definition
-- below mirrors the live `dev_staging` catalog column-for-column (verified
-- 2026-10-10), and every statement is idempotent, so replaying this file is
-- always safe.
--
-- WHY THIS EXISTS: the website staging range renders CMS-owned header
-- chrome, footer identity, portrait shapes, portfolio buttons, skill links
-- and the request intake against these objects. The production build fails
-- prerendering without them (PGRST205 on `public.site_settings`).
--
-- SCOPE DISCIPLINE (do not widen in this file):
-- - `site_settings` is created WITHOUT the retired `nav_anchors` column and
--   WITHOUT `footer_name`: neither exists in dev_staging anymore, and the
--   website reads nav items and the footer name from site-side constants.
-- - `project_requests` holds visitor personal data: no anon/authenticated
--   grants, no public policies, never cached (mirrors the dev posture).
-- - New columns are nullable with no backfill: existing rows keep rendering
--   exactly as before until an editor fills them in.
-- - No data is written by this file. Content promotion is a separate,
--   explicitly authorized step.
--
-- ── site_settings (singleton CMS configuration) ─────────────────────────

create table if not exists public.site_settings (
  id bigint primary key generated by default as identity,
  created_at timestamptz not null default now(),
  footer_vat_number text,
  header_logo_dark text,
  header_logo_light text
);

comment on table public.site_settings is
  'Single-row site configuration. Header chrome and footer identity the CMS owns; NULL means "never configured" and the public site falls back to its bundled assets and default identity.';

comment on column public.site_settings.footer_vat_number is
  'Footer VAT number, stored as text so a leading zero survives. NULL renders the default number; an empty string is treated as NULL by the reader.';

comment on column public.site_settings.header_logo_dark is
  'Absolute URL of the dark-theme header logo. NULL renders the bundled title-ws.png; an empty string is treated as NULL by the reader.';

comment on column public.site_settings.header_logo_light is
  'Absolute URL of the light-theme header logo. NULL renders the bundled title-ws-lightmode.png; an empty string is treated as NULL by the reader. Resolved per theme, so storing one variant never blanks the other.';

-- The public site reads this with the publishable (anon) key; the CMS
-- writes through the service-role client (BYPASSRLS).
grant usage on schema public to anon, authenticated, service_role;
grant select on table public.site_settings to anon, authenticated;
grant select, insert, update, delete on table public.site_settings
  to service_role;
grant usage, select on sequence public.site_settings_id_seq
  to service_role;

alter table public.site_settings enable row level security;

drop policy if exists site_settings_public_read on public.site_settings;
create policy site_settings_public_read on public.site_settings
  for select to anon, authenticated using (true);

-- ── project_requests (visitor personal data, service_role only) ──────────

create table if not exists public.project_requests (
  id bigint primary key generated by default as identity,
  created_at timestamptz not null default now(),
  locale text not null default 'en'
    check (locale in ('en', 'it')),
  name text not null,
  email text not null,
  company text not null default '',
  website text not null default '',
  project_type text not null
    check (project_type in ('Website', 'Web app', 'Mobile app', 'Other')),
  budget text not null
    check (budget in ('< €1k', '€1–5k', '€5–15k', '€15k+')),
  timeline text not null
    check (timeline in ('ASAP', '1–2 months', '3–6 months', 'Flexible')),
  request text not null,
  consent boolean not null,
  archived boolean not null default false,
  archived_at timestamptz
);

comment on table public.project_requests is
  'Project requests submitted through the public form. Personal data: service_role only, no anon/authenticated grants, never publicly cached.';

comment on column public.project_requests.project_type is
  'Project type option (the public form field is named `type`).';

comment on column public.project_requests.archived is
  'Boolean archive flag: false = active inbox row, true = archived. The CMS filters on this single predicate.';

comment on column public.project_requests.archived_at is
  'When the row was archived; null while active.';

-- Active-first listing is the inbox default view.
create index if not exists project_requests_active_idx
  on public.project_requests (archived, created_at desc);

-- RLS on with NO policies: anon/authenticated own no rows, and service_role
-- bypasses RLS outright.
alter table public.project_requests enable row level security;

-- Supabase tables default to SELECT granted to PUBLIC (anon/authenticated
-- inherit it), so revoke from `public` too.
revoke all on table public.project_requests from public;
revoke all on table public.project_requests from anon, authenticated;

grant select, insert, update, delete on table public.project_requests
  to service_role;
grant usage, select on sequence public.project_requests_id_seq
  to service_role;

-- ── CMS-owned columns on existing content tables ─────────────────────────
-- All nullable, no backfill: no-op for existing rows until edited.

alter table public.hero_section
  add column if not exists shape text;

comment on column public.hero_section.shape is
  'Portrait preset: pebble | square | rounded | squircle. Null renders pebble.';

alter table public.portfolio_posts
  add column if not exists buttons jsonb;

comment on column public.portfolio_posts.buttons is
  'Ordered quick-link buttons: [{kind, url, label?}] where kind is website|source|demo|store|fdroid|ios|custom. Array order is render order; label is read only for custom. NULL/empty falls back to the legacy link columns.';

alter table public.skills
  add column if not exists link text;

alter table public.skills
  add column if not exists position integer;

comment on column public.skills.link is
  'Optional http(s) URL rendered as an external link on the public skill tile.';

comment on column public.skills.position is
  'Order of the skill inside its category; NULL sorts last (never ordered).';

-- REVERSIBLE (only if the website release that needs these objects is also
-- reverted; otherwise the production build fails prerendering):
--
--   drop table if exists public.project_requests;
--   drop table if exists public.site_settings;
--   alter table public.hero_section drop column if exists shape;
--   alter table public.portfolio_posts drop column if exists buttons;
--   alter table public.skills drop column if exists link;
--   alter table public.skills drop column if exists position;
